//! GI2-4 — free-running greedy decode + agreement/first-divergence record tests.
//!
//! Families:
//! 1. **Record contract (§4.5)**: serialization round-trip + the committed
//!    run-record self-consistency check (schema, divergence-field `none`,
//!    first-diverging position == first token mismatch vs the embedded
//!    `TRACE_TOKENS`, token-level, never text-level).
//! 2. **Greedy-loop mechanics on the real oracle** (bounded prefix, default
//!    lane): 3 free-running positions from the 9 pinned prompt tokens match
//!    the trace head — proves the free-running loop (EOG-excluded argmax,
//!    prediction feedback, finite gate) is not masked by the teacher-forced
//!    window.
//! 3. **Full 256-token acceptance run** (`#[ignore]` — ~30 min in the debug
//!    test profile; opt-in like the numeric golden cross-check): the free-
//!    running decode over all 256 positions, byte-stable vs the committed
//!    run record, all finite, §4.5 divergence record correct. The committed
//!    record is generated by the env-gated emitter (`FABER_GI24_EMIT_RECORD=1`)
//!    and is what the record tests validate.
//!
//! Model-dependent tests follow the `tensor_view_test` / `cpu_oracle_test`
//! convention: skipped (with a loud note) when the pinned row is absent.

use crate::cpu_oracle::{
    top1_non_eog, CpuOracle, ForwardRun, EOG_TOKENS, FailingThreshold, VOCAB_SIZE,
    WINDOW_POSITIONS,
};
use crate::gguf::{admit_gguf, hex, sha256, PINNED_SHA256_HEX};
use crate::greedy_run::*;
use crate::json::Json;
use crate::tensor_view::TensorView;
use crate::valor::Valor;
use std::collections::BTreeMap;

/// Machine-local pinned row (skipped when absent — same convention as the
/// GI2-3 oracle tests).
const PINNED_MODEL_PATH: &str = "/Users/ianzepp/ai/models/SmolLM2-360M-Instruct-Q4_K_M.gguf";

/// The committed comparator logp reference window (17×49152 f32 LE,
/// position-major) — used only for the §4.3 band at a diverging position
/// inside the captured window; the same fixture the GI2-3 comparison pins.
const LOGP_REFERENCE_REL_PATH: &str =
    "../radix/docs/factory/gpu-inference-gguf/evidence/gi2-3-logp-reference.bin";
const LOGP_REFERENCE_SHA256_HEX: &str =
    "d105b49bde0ee5070020bb3a545578ba1195900937f44446893ad3bbaabad8ec";

/// Committed GI2-4 run record (Q3 default: crate-local testdata).
const RECORD_REL_DIR: &str = "testdata/gi2-4-greedy-record";

fn pinned_model_bytes() -> Option<Vec<u8>> {
    let path = std::path::Path::new(PINNED_MODEL_PATH);
    if !path.exists() {
        eprintln!("SKIP: pinned model not present at {PINNED_MODEL_PATH}");
        return None;
    }
    std::fs::read(path).ok()
}

fn record_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RECORD_REL_DIR)
}

fn build_pinned_view(bytes: &[u8]) -> TensorView<'_> {
    let admission = admit_gguf(bytes).expect("pinned row must admit");
    let view = TensorView::build(&admission, bytes).expect("view must build");
    assert!(view.coverage_ok(), "the pinned view must tile exactly");
    assert_eq!(view.sha256_hex(), PINNED_SHA256_HEX, "pinned row identity");
    view
}

fn shared_oracle() -> Option<&'static CpuOracle> {
    static ORACLE: std::sync::OnceLock<Option<CpuOracle>> = std::sync::OnceLock::new();
    ORACLE
        .get_or_init(|| {
            if !std::path::Path::new(PINNED_MODEL_PATH).exists() {
                eprintln!("SKIP: pinned model not present at {PINNED_MODEL_PATH}");
                return None;
            }
            let bytes = std::fs::read(PINNED_MODEL_PATH).expect("pinned model read");
            let bytes: &'static [u8] = Box::leak(bytes.into_boxed_slice());
            let view = build_pinned_view(bytes);
            Some(CpuOracle::build(&view).expect("oracle build"))
        })
        .as_ref()
}

/// Load the committed comparator logp window (17×49152 f32 LE), skipping
/// loudly when the sibling radix layout moved.
fn load_logp_window() -> Option<Vec<f32>> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(LOGP_REFERENCE_REL_PATH);
    let bytes = match std::fs::read(&path) {
        Ok(bytes) => bytes,
        Err(err) => {
            eprintln!(
                "SKIP: comparator logp reference not readable at {} ({err})",
                path.display()
            );
            return None;
        }
    };
    assert_eq!(
        hex(&sha256(&bytes)),
        LOGP_REFERENCE_SHA256_HEX,
        "logp reference fixture must be hash-pinned"
    );
    assert_eq!(bytes.len(), WINDOW_POSITIONS * VOCAB_SIZE * 4);
    Some(
        bytes
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect(),
    )
}

// -- Valor walking helpers (same pattern as cpu_oracle_test) ----------------

fn text(v: &Valor) -> &str {
    let Valor::Textus(s) = v else {
        panic!("expected JSON string")
    };
    s
}

fn int(v: &Valor) -> i64 {
    let Valor::Numerus(n) = v else {
        panic!("expected JSON integer")
    };
    *n
}

fn flag(v: &Valor) -> bool {
    let Valor::Bivalens(b) = v else {
        panic!("expected JSON boolean")
    };
    *b
}

fn list<'a>(v: &'a Valor) -> &'a [Valor] {
    let Valor::Lista(items) = v else {
        panic!("expected JSON array")
    };
    items
}

fn field<'a>(v: &'a Valor, key: &str) -> &'a Valor {
    let Valor::Tabula(fields) = v else {
        panic!("expected JSON object")
    };
    fields
        .get(key)
        .unwrap_or_else(|| panic!("missing JSON field {key:?}"))
}

// ---------------------------------------------------------------------------
// 1. Record contract (§4.5): serialization round-trip + committed record
// ---------------------------------------------------------------------------

#[test]
fn record_serialization_round_trips_and_divergence_field() {
    // Serialize a synthetic record, parse it back, and verify every §4.5
    // field survives. No model needed.
    let record = GreedyRunRecord {
        generated_tokens: TRACE_TOKENS[..16].to_vec(),
        all_finite: true,
        first_divergence: Some(GreedyDivergence {
            position: 3,
            comparator_trace_token: TRACE_TOKENS[3],
            oracle_token: 9,
            failing_thresholds: vec![FailingThreshold::Top1, FailingThreshold::Band],
            max_band_deviation: Some(2.1e-2),
        }),
    };
    let wire = record_to_json(&record);
    let root = Json::parse(&wire).expect("record parses").as_valor().clone();
    assert_eq!(text(field(&root, "schema")), RECORD_SCHEMA);
    assert_eq!(int(field(&root, "generated_token_count")), 16);
    assert_eq!(flag(field(&root, "all_finite")), true);
    assert_eq!(flag(field(&root, "all_agree")), false);
    assert_eq!(list(field(&root, "generated_tokens")).len(), 16);

    let div = field(&root, "first_divergence");
    let is_tabula = matches!(div, Valor::Tabula(_));
    assert!(is_tabula, "first_divergence must be an object, got {div:?}");
    assert_eq!(int(field(div, "position")), 3);
    assert_eq!(int(field(div, "comparator_trace_token")), TRACE_TOKENS[3]);
    assert_eq!(int(field(div, "oracle_token")), 9);
    let failing_thresholds = list(field(div, "failing_thresholds"));
    assert_eq!(failing_thresholds.len(), 2);
    assert_eq!(text(&failing_thresholds[0]), "top-1");
    assert_eq!(text(&failing_thresholds[1]), "band");
    // The divergence field (human readout) is token-level, never text-level.
    assert!(record.divergence_field().starts_with("position 3"));

    // A fully-agreeing record has divergence field `none`.
    let ok = GreedyRunRecord {
        generated_tokens: TRACE_TOKENS[..4].to_vec(),
        all_finite: true,
        first_divergence: None,
    };
    let wire_ok = record_to_json(&ok);
    let root_ok = Json::parse(&wire_ok).expect("ok record parses").as_valor().clone();
    assert!(matches!(field(&root_ok, "first_divergence"), Valor::Nihil));
    assert_eq!(ok.divergence_field(), "none");
}

#[test]
fn committed_greedy_record_is_schema_valid_and_self_consistent() {
    // The committed run record (the GI2-4 receipt) must be present, match
    // its schema, and be self-consistent with the embedded trace: the
    // first-diverging position is exactly the first token mismatch between
    // the committed generated tokens and TRACE_TOKENS, the divergence field
    // is `none` exactly when the full trace agrees, and the finite gate
    // holds. When the record is absent (the full 256-token run is an opt-in
    // ~25-min compute), this skips loudly — the record fixture is required
    // for the strict assertion, exactly like the pinned-model skip.
    let dir = record_dir();
    let wire = match std::fs::read_to_string(dir.join("record.json")) {
        Ok(wire) => wire,
        Err(err) => {
            eprintln!(
                "SKIP: committed greedy run record absent at {} ({err}); emit it with FABER_GI24_EMIT_RECORD=1 (full 256-token run, ~25 min debug profile)",
                dir.display(),
            );
            return;
        }
    };
    let root = Json::parse(&wire).expect("record parses").as_valor().clone();

    assert_eq!(text(field(&root, "schema")), RECORD_SCHEMA);
    let n = int(field(&root, "generated_token_count"));
    assert_eq!(n, GREEDY_TOKEN_COUNT as i64, "the committed record is the full 256-token run");

    let generated: Vec<i64> = list(field(&root, "generated_tokens"))
        .iter()
        .map(int)
        .collect();
    assert_eq!(generated.len(), GREEDY_TOKEN_COUNT);
    assert!(
        generated.iter().all(|&t| (0..VOCAB_SIZE as i64).contains(&t)),
        "all generated token ids must be in [0, vocab_size)"
    );

    // The first token mismatch vs the embedded trace defines the §4.5 record.
    let first_mismatch = generated
        .iter()
        .zip(TRACE_TOKENS.iter())
        .position(|(o, c)| o != c);
    let all_agree = first_mismatch.is_none();
    assert_eq!(
        flag(field(&root, "all_agree")),
        all_agree,
        "all_agree must equal (no token mismatch vs the trace)"
    );

    match field(&root, "first_divergence") {
        Valor::Nihil => {
            assert!(all_agree, "divergence field must be none only when the full trace agrees");
        }
        div => {
            let pos = int(field(div, "position"));
            assert_eq!(Some(pos as usize), first_mismatch, "the record is taken at the FIRST diverging position");
            assert_eq!(
                int(field(div, "comparator_trace_token")),
                TRACE_TOKENS[pos as usize],
                "record carries the comparator trace token"
            );
            assert_eq!(
                int(field(div, "oracle_token")),
                generated[pos as usize],
                "record carries the oracle token"
            );
            let failing: Vec<String> = list(field(div, "failing_thresholds"))
                .iter()
                .map(text)
                .map(ToOwned::to_owned)
                .collect();
            assert!(
                !failing.is_empty(),
                "failing thresholds must be named at a divergence"
            );
            // Band deviation is only inside the captured 17-position window.
            if pos < WINDOW_POSITIONS as i64 {
                assert!(
                    matches!(field(div, "max_band_deviation"), Valor::Fractus(_)),
                    "band deviation must be recorded inside the captured window (pos {pos})"
                );
            } else {
                assert!(
                    matches!(field(div, "max_band_deviation"), Valor::Nihil),
                    "band deviation must be absent beyond the captured window (pos {pos})"
                );
            }
        }
    }
    assert_eq!(flag(field(&root, "all_finite")), true, "finite gate must hold");

    // The trace provenance is hash-accounted in the committed record.
    let trace = field(&root, "trace");
    assert_eq!(text(field(trace, "schema")), TRACE_SCHEMA);
    assert_eq!(text(field(trace, "file_sha256")), TRACE_FILE_SHA256_HEX);
}

// ---------------------------------------------------------------------------
// 2. Greedy-loop mechanics on the real oracle (bounded prefix, default lane)
// ---------------------------------------------------------------------------

#[test]
fn greedy_loop_short_prefix_is_free_running_and_matches_trace_head() {
    let Some(oracle) = shared_oracle() else {
        return;
    };
    // 3 free-running positions: the prediction is fed back (never
    // teacher-forced), EOG {0,2} excluded, finite gate checked.
    let record = run_greedy(oracle, &TRACE_TOKENS[..3], None).expect("greedy run");
    assert_eq!(record.generated_tokens.len(), 3);
    assert_eq!(
        record.generated_tokens,
        [TRACE_TOKENS[0], TRACE_TOKENS[1], TRACE_TOKENS[2]],
        "the free-running greedy head must match the pinned trace head (top-1 exact, GI2-3)"
    );
    assert!(record.all_finite, "finite gate at every covered position");
    assert_eq!(record.first_divergence, None, "no divergence in the prefix");
    assert_eq!(record.divergence_field(), "none");

    // The prefix run is genuinely free-running: the second generated token
    // comes from feeding the first prediction, not from the trace.
    let mut run = ForwardRun::new(oracle, &PROMPT_TOKENS).expect("run");
    let first_logits = run.position_logits().expect("position 0");
    let first = top1_non_eog(&first_logits, &EOG_TOKENS);
    assert_eq!(first, TRACE_TOKENS[0]);
    run.push_token(first).expect("feed own prediction");
    let second_logits = run.position_logits().expect("position 1");
    let second = top1_non_eog(&second_logits, &EOG_TOKENS);
    assert_eq!(second, TRACE_TOKENS[1]);
    assert_eq!(
        record.generated_tokens[1], second,
        "greedy loop must feed its own prediction"
    );
}

// ---------------------------------------------------------------------------
// 3. Full 256-token acceptance run (opt-in; the committed record's source)
// ---------------------------------------------------------------------------

/// One-time emission of the committed run record (env-gated). Run with
/// `FABER_GI24_EMIT_RECORD=1` to (re)generate the record + manifest under
/// `testdata/gi2-4-greedy-record/`. The full 256-token free-running decode
/// takes ~20-40 min in the debug test profile (documented tool_latency).
#[test]
fn emit_greedy_record_when_requested() {
    let Some(bytes) = pinned_model_bytes() else {
        return;
    };
    if std::env::var_os("FABER_GI24_EMIT_RECORD").is_none() {
        eprintln!("set FABER_GI24_EMIT_RECORD=1 to (re)emit the committed greedy run record");
        return;
    }
    let view = build_pinned_view(&bytes);
    let oracle = CpuOracle::build(&view).expect("oracle build");
    let window = load_logp_window();
    let record = run_greedy(&oracle, &TRACE_TOKENS, window.as_deref()).expect("full greedy run");
    let dir = record_dir();
    std::fs::create_dir_all(&dir).expect("create record dir");
    let wire = record_to_json(&record);
    std::fs::write(dir.join("record.json"), wire).expect("write record");
    let manifest = build_manifest(&view, &record);
    std::fs::write(dir.join("manifest.json"), manifest).expect("write manifest");
    eprintln!(
        "wrote GI2-4 greedy run record to {}: {}",
        dir.display(),
        record.divergence_field()
    );
}

/// The committed record manifest: schema/model/trace provenance + hash
/// accounting.
fn build_manifest(view: &TensorView<'_>, record: &GreedyRunRecord) -> String {
    let mut root = BTreeMap::new();
    root.insert("schema".to_string(), Valor::from(RECORD_MANIFEST_SCHEMA));
    let mut model = BTreeMap::new();
    model.insert("sha256".to_string(), Valor::from(view.sha256_hex()));
    model.insert("bytes".to_string(), Valor::from(view.file_size() as i64));
    root.insert("model".to_string(), model.into());
    let mut trace = BTreeMap::new();
    trace.insert("schema".to_string(), Valor::from(TRACE_SCHEMA));
    trace.insert(
        "comparator_revision".to_string(),
        Valor::from(TRACE_COMPARATOR_REVISION),
    );
    trace.insert(
        "file_sha256".to_string(),
        Valor::from(TRACE_FILE_SHA256_HEX),
    );
    root.insert("trace".to_string(), trace.into());
    let wire = record_to_json(record);
    let mut entry = BTreeMap::new();
    entry.insert("file".to_string(), Valor::from("record.json"));
    entry.insert(
        "sha256".to_string(),
        Valor::from(hex(&sha256(wire.as_bytes()))),
    );
    entry.insert(
        "generated_token_count".to_string(),
        Valor::from(record.generated_tokens.len() as i64),
    );
    root.insert(
        "fixtures".to_string(),
        Valor::from(vec![Valor::from(entry)]),
    );
    let json = Json::from_object(root).expect("manifest JSON is valid");
    format!("{}\n", json.to_wire())
}

/// The full 256-token acceptance run (opt-in — ~20-40 min in the debug test
/// profile): free-running decode over all 256 positions, byte-identical to
/// the committed run record, all finite, §4.5 divergence record correct.
/// Run with `cargo nextest run -p faber-runtime -E 'test(greedy_256_run)'
/// --run-ignored all`.
#[test]
#[ignore = "full 256-token free-running decode (~20-40 min debug profile); the committed record is the default-lane evidence"]
fn greedy_256_run_matches_embedded_trace() {
    let Some(oracle) = shared_oracle() else {
        return;
    };
    let window = load_logp_window();
    let record = run_greedy(&oracle, &TRACE_TOKENS, window.as_deref()).expect("full greedy run");
    assert_eq!(record.generated_tokens.len(), GREEDY_TOKEN_COUNT);
    assert!(record.all_finite, "finite gate at every covered position");

    // Byte-stable vs the committed record (the run is deterministic).
    let wire = record_to_json(&record);
    let committed = std::fs::read_to_string(record_dir().join("record.json"))
        .expect("committed record must exist (emit with FABER_GI24_EMIT_RECORD=1)");
    assert_eq!(
        wire, committed,
        "the full run must be byte-identical to the committed record"
    );

    // §4.5: the record is taken at the FIRST diverging position, token-level.
    match &record.first_divergence {
        None => {
            assert!(
                record
                    .generated_tokens
                    .iter()
                    .zip(TRACE_TOKENS.iter())
                    .all(|(o, c)| o == c),
                "divergence field must be none only when the full trace agrees"
            );
            eprintln!("GI2-4 verdict: divergence field = none (all 256 generated tokens match the comparator trace)");
        }
        Some(d) => {
            let pos = d.position as usize;
            assert!(
                record.generated_tokens[pos] != TRACE_TOKENS[pos]
                    && record.generated_tokens[..pos]
                        .iter()
                        .zip(TRACE_TOKENS[..pos].iter())
                        .all(|(o, c)| o == c),
                "the record must be at the FIRST diverging position"
            );
            eprintln!(
                "GI2-4 verdict: {d} (all finite = {})",
                record.all_finite
            );
        }
    }
}
